backend:
  name: github
  repo: TeeWallz/astro-decap-monty
  branch: main
  site_domain: astro.howmanydayssincemontaguestreetbridgehasbeenhit.com
  base_url: https://sveltia-cms-auth.tomku.workers.dev
  # auth_endpoint:
  squash_merges: true
  # open_authoring: true

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://astro-decapcms-starter.netlify.app/" # your site name

collections:
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - {label: "Publish", name: "isPublish", widget: "boolean", default: true}
      - {label: "Draft", name: "isDraft", widget: "boolean", default: false}
      - { name: body, label: Body, widget: markdown }